# Generated by Django 3.2 on 2023-02-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='song_count',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='artist',
            name='birth_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
