# Generated by Django 3.2 on 2023-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20230221_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='music_video',
            field=models.BooleanField(default=False),
        ),
    ]
