# Generated by Django 3.2 on 2023-02-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20230221_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.CharField(max_length=10),
        ),
    ]
