# Generated by Django 3.2 on 2023-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_song_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
